#!/bin/bash

# ==============================================================================
# PROXMOX HOST INITIAL SETUP & HARDENING (DEBIAN 13 / TRIXIE)
# Custom VPS configuration tailored for Promox Virtual Environment Hosts
# Run this LOCALLY on the VPS (not via SSH) BEFORE installing Proxmox packages
# ==============================================================================

set -euo pipefail

# Determine script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load utilities library
if [ -f "${SCRIPT_DIR}/lib/utils.sh" ]; then
    source "${SCRIPT_DIR}/lib/utils.sh"
else
    echo "ERROR: Utilities library not found!"
    exit 1
fi
# Load OS detection library
if [ -f "${SCRIPT_DIR}/lib/os-detect.sh" ]; then
    source "${SCRIPT_DIR}/lib/os-detect.sh"
else
    echo "ERROR: OS detection library not found!"
    exit 1
fi
# Load secrets library (password generation)
if [ -f "${SCRIPT_DIR}/lib/secrets.sh" ]; then
    source "${SCRIPT_DIR}/lib/secrets.sh"
else
    echo "ERROR: Secrets library not found!"
    exit 1
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }
log_step() { echo -e "${BLUE}>>> $1${NC}"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }

# Banner
print_banner() {
    clear
    cat << 'EOF'
╔═══════════════════════════════════════════════════════════╗
║           VPS ORCHESTRATOR                                ║
║           Proxmox Host Setup & Hardening                  ║
╚═══════════════════════════════════════════════════════════╝
EOF
    echo ""
    log_info "Detected OS: $(get_os_info)"
    
    if ! is_debian_based; then
        log_error "This script is strictly for Debian-based systems (specifically Debian 13 / Trixie) hosting Proxmox."
        exit 1
    fi
    echo ""
    
    # Initialize audit logging
    audit_log "PROXMOX_SETUP_START" "system" "$(get_os_info)"
}

# Gather user input
gather_information() {
    log_step "Configuration Input Required"
    echo ""
    
    # Hostname & FQDN
    while true; do
        echo -ne "${YELLOW}Enter base hostname for Proxmox (e.g., proxmox-ryzen7):${NC} "
        read -r PVE_HOSTNAME
        
        if [ -z "$PVE_HOSTNAME" ]; then
            log_error "Hostname cannot be empty"
            continue
        fi
        
        # Validare bazica RFC 1123 pentru hostname
        if [[ ! "$PVE_HOSTNAME" =~ ^[a-zA-Z0-9-]{1,63}$ ]]; then
            log_error "Invalid hostname format (use alphanumeric and hyphens only)"
            continue
        fi
        break
    done

    # New username
    while true; do
        echo -ne "${YELLOW}Enter new admin username:${NC} "
        read -r NEW_USER
        
        if [ -z "$NEW_USER" ]; then
            log_error "Username cannot be empty"
            continue
        fi
        
        if [[ ! "$NEW_USER" =~ ^[a-z_][a-z0-9_-]{2,31}$ ]]; then
            log_error "Invalid username (use lowercase, 3-32 chars)"
            continue
        fi
        
        if id "$NEW_USER" &>/dev/null; then
            log_warn "User $NEW_USER already exists"
            echo -ne "${YELLOW}Use existing user? (y/n):${NC} "
            read -r choice
            if [[ "$choice" =~ ^[Yy]$ ]]; then
                break
            fi
            continue
        fi
        
        break
    done
    
    # New admin user password - generated by lib/secrets.sh
    GENERATED_USER_PASSWORD=$(generate_system_password 20)
    log_info "Strong password auto-generated for user '$NEW_USER'."
    
    # SSH port
    while true; do
        echo -ne "${YELLOW}Enter new SSH port [Default port 22]:${NC} "
        read -r SSH_PORT
        SSH_PORT=${SSH_PORT:-22}
        
        if [[ ! "$SSH_PORT" =~ ^[0-9]+$ ]] || [ "$SSH_PORT" -lt 1024 ] || [ "$SSH_PORT" -gt 65535 ]; then
            log_error "Port must be between 1024 and 65535"
            continue
        fi
        
        break
    done
    
    echo ""
    log_info "Configuration Summary:"
    echo "  Hostname: $PVE_HOSTNAME"
    echo "  Username: $NEW_USER"
    echo "  SSH Port: $SSH_PORT"
    echo ""
    
    echo "Your connection will be interrupted when SSH is restarted."
    echo "After setup, connect using the new username and port."
    echo ""

    echo -ne "${YELLOW}Proceed with setup? (yes/no):${NC} "
    read -r confirm
    if [[ "$confirm" != "yes" ]]; then
        log_info "Setup cancelled"
        exit 0
    fi
}

configure_hostname_fqdn() {
    log_step "Step 1: Network Hostname & FQDN"
    
    # Set the hostname
    run_sudo hostnamectl set-hostname "$PVE_HOSTNAME"
    
    # Update /etc/hosts with public IP
    local PUBLIC_IP
    # Încearcă să extragă IP-ul public asociat interfeței principale
    PUBLIC_IP=$(ip -4 addr show scope global | grep inet | awk '{print $2}' | cut -d/ -f1 | head -n 1)
    
    if [ -z "$PUBLIC_IP" ]; then
        log_warn "Could not determine public IP automatically. Falling back to 127.0.1.1"
        PUBLIC_IP="127.0.1.1"
    fi

    # Elimină intrările vechi legate de IP-ul curent din /etc/hosts
    run_sudo sed -i "/$PUBLIC_IP/d" /etc/hosts
    
    # Adaugă intrarea FQDN pentru Proxmox
    echo "${PUBLIC_IP} ${PVE_HOSTNAME}.local ${PVE_HOSTNAME}" | run_sudo tee -a /etc/hosts > /dev/null
    
    # Adaugă și loopback-ul dacă nu există
    if ! grep -q "127.0.0.1.*localhost" /etc/hosts; then
        echo "127.0.0.1 localhost" | run_sudo tee -a /etc/hosts > /dev/null
    fi

    log_success "Hostname set to $PVE_HOSTNAME and /etc/hosts updated with FQDN."
}

# System update and Repository Prep
system_update() {
    log_step "Step 2: System Update & Repository Preparation"
    
    # Wait for apt locks
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
        log_info "Waiting for other package managers to finish..."
        sleep 5
    done
    
    # Add non-free-firmware to Debian 13 sources for Microcode
    log_info "Ensuring non-free and non-free-firmware are enabled..."
    
    # Debian 13 often uses DEB822 format in /etc/apt/sources.list.d/debian.sources
    local APT_SOURCES_FILE="/etc/apt/sources.list"
    if [ -f "/etc/apt/sources.list.d/debian.sources" ]; then
        APT_SOURCES_FILE="/etc/apt/sources.list.d/debian.sources"
        # For DEB822 format, append to the Components line if not already there
        if ! grep -q "non-free-firmware" "$APT_SOURCES_FILE"; then
            run_sudo sed -i -r 's/^(Components:.*)/\1 contrib non-free non-free-firmware/' "$APT_SOURCES_FILE"
        fi
    elif [ -f "$APT_SOURCES_FILE" ]; then
        # Traditional format
        run_sudo sed -i -r 's/^(deb( src)? .* (trixie|trixie-updates|trixie-security) .*)(main) *$/\1\4 contrib non-free non-free-firmware/' "$APT_SOURCES_FILE"
    else
        log_warn "Could not find standard APT sources file. Skipping non-free-firmware injection."
    fi
    
    log_info "Updating package index..."
    pkg_update
    
    log_info "Upgrading packages..."
    run_sudo env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    run_sudo apt-get autoremove -y
    
    log_success "System updated and repositories prepared"
}

# Install tools and Microcode
install_system_tools() {
    log_step "Step 3: Installing Essential Tools & CPU Microcode"
    
    local packages="curl wget git htop vim ncdu sudo fail2ban auditd chrony apt-listchanges net-tools libpam-tmpdir"
    
    # Determine CPU Vendor for microcode
    if grep -q "AuthenticAMD" /proc/cpuinfo; then
        packages="$packages amd64-microcode"
        log_info "AMD CPU detected. Including amd64-microcode."
    elif grep -q "GenuineIntel" /proc/cpuinfo; then
        packages="$packages intel-microcode"
        log_info "Intel CPU detected. Including intel-microcode."
    fi

    log_info "Installing: $packages"
    pkg_install $packages
    
    log_success "System tools and microcode installed"
}

# Prepare Proxmox 9 Repositories
prepare_proxmox_repo() {
    log_step "Step 4: Proxmox 9 Repository Setup (Trixie)"

    log_info "Downloading Proxmox Release GPG Key..."
    run_sudo wget -q https://enterprise.proxmox.com/debian/proxmox-release-trixie.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-trixie.gpg
    
    # Remove enterprise repo if it exists (prevents 401 Unauthorized errors on free tier)
    log_info "Ensuring Proxmox Enterprise repository is removed..."
    run_sudo rm -f /etc/apt/sources.list.d/pve-enterprise.list
    run_sudo rm -f /etc/apt/sources.list.d/pve-enterprise.sources
    run_sudo rm -f /etc/apt/sources.list.d/ceph.list
    run_sudo rm -f /etc/apt/sources.list.d/ceph.sources
    
    # Also check if it was added to the main sources list or debian.sources
    local APT_SOURCES_FILE="/etc/apt/sources.list"
    if [ -f "/etc/apt/sources.list.d/debian.sources" ]; then
        run_sudo sed -i '/enterprise.proxmox.com/d' /etc/apt/sources.list.d/debian.sources
    fi
    if [ -f "$APT_SOURCES_FILE" ]; then
        run_sudo sed -i '/enterprise.proxmox.com/d' "$APT_SOURCES_FILE"
    fi

    log_info "Adding Proxmox 9 No-Subscription Repository (DEB822 format)..."
    run_sudo bash -c "cat > /etc/apt/sources.list.d/proxmox.sources" <<'EOF'
Types: deb
URIs: http://download.proxmox.com/debian/pve
Suites: trixie
Components: pve-no-subscription
Signed-By: /etc/apt/trusted.gpg.d/proxmox-release-trixie.gpg
EOF
    
    log_success "Proxmox repository configured."
}

# Create admin user
create_admin_user() {
    log_step "Step 5: Setting Up Admin User"
    
    local SUDO_GROUP="sudo"
    
    if ! id "$NEW_USER" &>/dev/null; then
        run_sudo useradd -m -s /bin/bash "$NEW_USER"
        echo "${NEW_USER}:${GENERATED_USER_PASSWORD}" | run_sudo chpasswd
        run_sudo usermod -aG "$SUDO_GROUP" "$NEW_USER"
        run_sudo loginctl enable-linger "$NEW_USER"
        log_success "User $NEW_USER created and added to $SUDO_GROUP group"
    else
        echo "${NEW_USER}:${GENERATED_USER_PASSWORD}" | run_sudo chpasswd
        run_sudo usermod -aG "$SUDO_GROUP" "$NEW_USER"
        run_sudo loginctl enable-linger "$NEW_USER"
        log_success "User $NEW_USER updated"
    fi

    # Set root password
    GENERATED_ROOT_PASSWORD=$(generate_system_password 20)
    echo "root:${GENERATED_ROOT_PASSWORD}" | run_sudo chpasswd
    log_success "Root password set (SSH login for root is going to be disabled)"

    USER_HOME="/home/$NEW_USER"
    
    # Environment Setup
    local USER_UID
    USER_UID=$(id -u "$NEW_USER")
    run_sudo mkdir -p "/run/user/$USER_UID"
    run_sudo chown "$NEW_USER:$NEW_USER" "/run/user/$USER_UID"
    run_sudo chmod 700 "/run/user/$USER_UID"

    {
        echo ""
        echo "# Standard umask for development"
        echo "umask 022"
    } | run_sudo tee -a "$USER_HOME/.bashrc" > /dev/null

    # Setup SSH directory
    run_sudo mkdir -p "$USER_HOME/.ssh"
    run_sudo chmod 700 "$USER_HOME/.ssh"
    
    # SSH Keys
    if [ -f "/root/.ssh/authorized_keys" ]; then
        log_info "Copying SSH keys from root..."
        run_sudo cp /root/.ssh/authorized_keys "$USER_HOME/.ssh/authorized_keys"
    else
        log_warn "No SSH keys found in /root/.ssh/authorized_keys"
        echo -ne "${YELLOW}Paste your SSH public key now (or press Enter to skip):${NC} "
        read -r SSH_KEY_INPUT
        if [ -n "$SSH_KEY_INPUT" ]; then
            if echo "$SSH_KEY_INPUT" | ssh-keygen -l -f - &>/dev/null 2>&1; then
                echo "$SSH_KEY_INPUT" | run_sudo tee "$USER_HOME/.ssh/authorized_keys" > /dev/null
                log_success "SSH public key validated and saved"
            else
                log_warn "Invalid SSH public key format! Skipping."
                run_sudo touch "$USER_HOME/.ssh/authorized_keys"
            fi
        else
            run_sudo touch "$USER_HOME/.ssh/authorized_keys"
        fi
    fi
    
    run_sudo chmod 600 "$USER_HOME/.ssh/authorized_keys"
    run_sudo chown -R "$NEW_USER:$NEW_USER" "$USER_HOME"
    
    log_success "User configuration completed"
}

# Configure SSH
configure_ssh() {
    log_step "Step 6: SSH Hardening"
    
    run_sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup_$(date +%Y%m%d_%H%M%S) || true
    
    local SSHD_CONFIG="# SSH Daemon Configuration - Hardened Proxmox Host
# Generated on $(date)

# Port and Protocol
Port $SSH_PORT
AddressFamily inet
Protocol 2

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Security
X11Forwarding no
PrintMotd no
PrintLastLog no
PermitUserEnvironment no
AllowTcpForwarding no
AllowAgentForwarding no
GatewayPorts no
MaxAuthTries 3
MaxSessions 2

# Timeouts
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

# Allowed users
AllowUsers $NEW_USER

# Include additional configs if they exist
Include /etc/ssh/sshd_config.d/*.conf"
    
    echo "$SSHD_CONFIG" | run_sudo tee /etc/ssh/sshd_config > /dev/null
    
    if ! run_sudo sshd -t 2>/dev/null; then
        log_error "SSH configuration is invalid! Restoring backup..."
        local LATEST_BACKUP=$(ls -t /etc/ssh/sshd_config.backup_* 2>/dev/null | head -1)
        if [ -n "$LATEST_BACKUP" ]; then
            run_sudo cp "$LATEST_BACKUP" /etc/ssh/sshd_config
        fi
        exit 1
    fi
    
    log_success "SSH configuration written (port $SSH_PORT)"
}


# Configure Fail2ban (SSH Only)
configure_fail2ban() {
    log_step "Step 7: Fail2ban Configuration (SSH)"
    
    local SSH_LOG_PATH="/var/log/auth.log"
    
    local FAIL2BAN_CONFIG="[DEFAULT]
bantime = 86400
findtime = 600
maxretry = 3
destemail = root@localhost
sendername = Fail2Ban
action = %(action_mw)s

# SQLite persistent DB
dbfile = /var/lib/fail2ban/fail2ban.sqlite3
dbpurgeage = 86400

[sshd]
enabled = true
port = $SSH_PORT
logpath = $SSH_LOG_PATH
maxretry = 3
bantime = 86400"
    
    echo "$FAIL2BAN_CONFIG" | run_sudo tee /etc/fail2ban/jail.local > /dev/null
    
    service_restart fail2ban
    service_enable fail2ban
    
    log_success "Fail2ban configured for SSH. (Note: Proxmox GUI jail for port 8006 can be added later)"
}

# Configure audit logs
configure_audit() {
    log_step "Step 8: Audit Logging"
    
    run_sudo bash -c "cat > /etc/audit/rules.d/audit.rules" <<'EOF'
# Monitor identity changes
-w /etc/passwd -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/sudoers -p wa -k sudoers
-w /etc/ssh/sshd_config -p warx -k sshd_config
EOF

    run_sudo systemctl restart auditd || true
    log_success "Audit logging configured"
}

# Main execution
main() {
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root"
        exit 1
    fi
    
    if [ -n "${SSH_CONNECTION:-}" ] || [ -n "${SSH_CLIENT:-}" ] || [ -n "${SSH_TTY:-}" ]; then
        echo ""
        log_warn "⚠️  DANGER: This script is being run over SSH!"
        log_warn "This will RESTART SSH and change the port."
        echo -ne "${YELLOW}Type 'FORCE' to proceed anyway:${NC} "
        read -r confirm
        if [[ "$confirm" != "FORCE" ]]; then
            log_info "Setup cancelled"
            exit 0
        fi
        echo ""
    fi
    
    print_banner
    
    log_warn "Preparing Debian system for Proxmox VE installation."
    log_warn "No generic firewalls will be installed."
    echo ""
    
    gather_information
    echo ""
    
    configure_hostname_fqdn
    prepare_proxmox_repo
    system_update
    install_system_tools
    create_admin_user
    configure_ssh
    configure_fail2ban
    configure_audit
    
    echo ""
    log_success "═══════════════════════════════════════════"
    log_success "  Proxmox Host Pre-Setup Completed!"
    log_success "═══════════════════════════════════════════"
    echo ""
    
    log_info "Configuration Summary:"
    echo "  • FQDN:         $PVE_HOSTNAME.local"
    echo "  • Admin User:   $NEW_USER"
    echo "  • SSH Port:     $SSH_PORT (Apply after restart)"
    echo "  • Server IP:    $(hostname -I | awk '{print $1}')"
    echo ""
    log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_warn "  ⚠️  SAVE THESE CREDENTIALS NOW"
    log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "${GREEN}  Admin User: ${NC}${NEW_USER}"
    echo -e "${GREEN}  Password:   ${NC}${GENERATED_USER_PASSWORD}"
    echo ""
    echo -e "${YELLOW}  Root User:  ${NC}root"
    echo -e "${YELLOW}  Password:   ${NC}${GENERATED_ROOT_PASSWORD}"
    echo -e "${YELLOW}  Note:       ${NC}Root SSH disabled. Use 'su -' mapped over user."
    unset GENERATED_USER_PASSWORD GENERATED_ROOT_PASSWORD
    echo ""
    log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_warn "  NEXT STEPS FOR PROXMOX INSTALLATION"
    log_warn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  1. The new DEB822 proxmox.sources and GPG key are added."
    echo "  2. You must now manually install the kernel/packages."
    echo ""
    echo -e "  Run the following commands as root:"
    echo -e "${GREEN}  apt update${NC}"
    echo -e "${GREEN}  apt install proxmox-ve postfix open-iscsi chrony${NC}"
    echo ""
    echo "  Note: The SSH service needs to restart for the new port ($SSH_PORT) to take effect."
    echo "  Restart mapping by exiting the console or running: systemctl restart ssh"
    echo ""
}

main "$@"
